### ISSUE TITLE
Uploading fastq in Kbase App

### ISSUE THREAD

**Issue by jbholm** [kbaseapps/ReadsUtils#60]
Hi, 
I'm having trouble uploading a metagenome file to my Kbase narrative. The error I am receiving is from readsUtil, but there isn't enough detail to decipher the problem (see below). The data are loaded into the staging area, and this completed without an obvious error. 

1536182149.75 - CallbackServer[f46943c3-f1be-47da-be7c-57261dce422d]: "ReadsUtils.upload_reads" job threw an error, name="Server error", code=-32000, message="Invalid FASTQ file - Path: /kb/module/work/tmp/7d6f6941-a8bd-42a3-959a-ea0e22229204/343238_MG_host_removed_relabeled.fq. Input Staging : 343238_MG_host_removed_relabeled.fq.", data:

**Comment by meghandrake** [comment]
Hi there jbholm!  We have a KBase public Help Board forum where users can post their questions and interact with developers.
Would you be interested in posting your question there?  You would also be able to see every other issue posted previously, as well as comment on them.
If you are not interested in joining our Help Board, I will create an internal ticket to track your question and be a go-between for you and the developers.
Please advise. :)

**Comment by jbholm** [comment]
Thanks for the fast response! I’ll post to the public help board.

Best,
Johanna

Johanna B. Holm, PhD
Postdoctoral Fellow
Institute for Genome Sciences
jholm@som.umaryland.edu<mailto:jholm@som.umaryland.edu>

On Sep 5, 2018, at 5:46 PM, Meghan Drake <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This message originated from a non UMB, UMSOM, FPI, or UMMS email system. Whether the sender is known or not known, hover over any links before clicking and use caution opening attachments.



Hi there jbholm! We have a KBase public Help Board forum where users can post their questions and interact with developers.
Would you be interested in posting your question there? You would also be able to see every other issue posted previously, as well as comment on them.
If you are not interested in joining our Help Board, I will create an internal ticket to track your question and be a go-between for you and the developers.
Please advise. :)

**Comment by meghandrake** [comment]
Johanna,

Super, thank you!! This link will take you to a page about how to join the Help Board:
http://kbase.us/contact-us/

**Comment by MrCreosote** [comment]
This appears to be resolved, so closing
